dataset:
  dev: data/clean/df_aux_cleaned.parquet
  val: data/clean/df_val_cleaned.parquet
  test: data/clean/df_test_cleaned.parquet

model:
  model_id: Qwen/Qwen2.5-3B-Instruct
  # google/gemma-2-2b-it # worked with this, but was overheating
  fourbit: false        
  max_new_tokens: 2

decoding:
  temperatures: [0.0, 0.3, 0.7]
  top_ps: [0.9, 1.0]
  seeds: [0, 1, 2] # was 1 before now changed to back to 0 1 2

# Store results
paths:
  results_dir: results
  val_raw: results/val_raw.csv
  val_summary: results/val_summary.csv
  test_final: results/test_final.csv

